### ISSUE TITLE
Merge b4e3ac5  from jacobkantrowitz into compbiomed?

### ISSUE THREAD

**Issue by antass** [SPIRBURG-inc/tableONE#2]
Thanks for the super useful package! I've been using the compbiomed version and noticed your personal commit b4e3ac5 has documentation and other improvements. Would you mind merging into compbiomed?

**Comment by definitelysean** [comment]
+1

**Comment by jacobkantrowitz** [comment]
looking into this. not yet great with git. should be done soon

**Comment by antass** [comment]
You should be able to send compbiomed a pull request. And then accept it
yourself (or maybe Sean would have to do it, not sure).

**Comment by antass** [comment]
Oh yeah. And no worries - I find it extremely unintuitive.
